version: '3.6'

services:
  visualizer:
    image: registry.services.alin.be/dockersamples/visualizer:latest
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M     
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.port=8080
        - traefik.frontend.rule=Host:visualizer.services.alin.be
        - traefik.frontend.entryPoints=http,https
        - traefik.backend.loadbalancer.method=wrr
      placement:
        constraints:
          - node.role == manager
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost"]
#      interval: 1m30s
#      timeout: 10s
#      retries: 3
#      start_period: 40s

networks:
  default:
    external:
      name: traefik-net