version: '3.4'

services:
  portainer:
    image: dockersamples/visualizer:latest
    privileged: true
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - ./data:/data
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
      labels:
        - traefik.port=8080
        - traefik.frontend.rule=Host:visualizer.services.alin.be
        - traefik.frontend.entryPoints=http,https
        - traefik.backend.loadbalancer.method=wrr
#        - traefik.backend=visualize
#    ports:
#     - "7098:8080"

networks:
  default:
    external:
      name: traefik-net
