version: '3.2'

services:
  portainer:
    image: dockersamples/visualizer
    container_name: visualizer
    ports:
     - "7098:8080"
    privileged: true
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - ./data:/data
    labels:
     - traefik.frontend.rule=Host:visualizer.services.alin.be
     - traefik.backend=visualizer
     - traefik.port=7098
     - traefik.frontend.entryPoints=https,http
    networks:
        - web

networks:
  web:
    external:
      name: traefik_webgateway
